name: SPACtivity
description: Keeps track of the traffic of the on-campus gyms at Northwestern University

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7

  google_maps_flutter: ^2.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
