import 'equipment.dart';

final List<Equipment> ListOfEquipment = [
  Equipment(id: '0', 
            name: '5 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '1', 
            name: '10 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),  
  Equipment(id: '2', 
            name: '15 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '3', 
            name: '20 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '4', 
            name: '25 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '5', 
            name: '30 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '6', 
            name: '35 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '7', 
            name: '40 lb Dummbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '8', 
            name: '45 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '9', 
            name: '50 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '10', 
            name: '55 lb Dumbbells',
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '11', 
            name: '60 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '12', 
            name: '65 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '13', 
            name: '70 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '14', 
            name: '75 lb Dumbbells', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
  Equipment(id: '15', 
            name: 'Adjustable Bench', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
  ),
  Equipment(id: '16', 
            name: 'Abdominal', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [ 
              'Step 1: Adjust seat height with lever under seat so legs are at 90 degree angle or the middle of torso is aligned with pivot point.',
              'Step 2: Place elbows on pads and grip handles.',
              'Step 3: Pull chest towards hips by contracting abdominals. Return to start position with controlled movement.',
            ],  
  ),
  Equipment(id: '17', 
            name: 'Assist Dip/Chin', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
              'Step 1: Step up and rotate handles to inner or outer position. Grip handles and place knees on pad.',
              'Step 2: Lower body with a controlled movement-torso upright/shoulders back. Do not exceed your comfortable range of motion. Return slowly.',
              'Step 3: When finished, bring knee pad all the way up to bring weight stack to rest.',
              'Step 4: Carefully step backwards onto steps and back down to floor.',
              'Step 1: Step up and grip desired hand position. Place knees on pad.',
              'Step 2: Slowly pull body upwards, then return with controlled movement, keeping chest up throughout the exercise.',
              'Step 3: When finished, bring knee pad all the way up to bring weight stack to rest.',
              'Step 4: Carefully step backwards onto steps and back down to floor.',
            ],  
  ),
  Equipment(id: '18', 
            name: 'Back Extension', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
  ),
  Equipment(id: '19', 
            name: 'Biceps Curl', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
              'Step 1: Adjust seat height so elbows align with pivot point (just off end of pad).',
              'Step 2: Grip handles firmly.',
              'Step 3: Keeping upper arms on pads, bend arms slowly to curled position and return.',
            ],  
  ),
  Equipment(id: '20', 
            name: 'Calf Extension', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
              'Step 1: Sit in seat and place feet on foot platform.',
              'Step 2: Adjust back pad so that knees are slightly bent while feet are on platform.',
              'Step 3: Slowly extend ankles. Keeping lower back and hips against back pad, and return.',
            ],  
  ),
  Equipment(id: '21', 
            name: 'Calf Raise', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions:[
              'Step 1: Load plates on each side for proper resistance',
              'Step 2: Sit and position your feet onto the foot pad. Lower the knee pad to your thighs and sit up tall.',
              'Step 3: Lift up and move release lever to the side.',
              'Step 4: Grip handles. Slowly, lower and lift through heels, pushing up through the balls of your feet.',
            ],  
  ),
  Equipment(id: '22', 
            name: 'Chest Press', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height with lever under seat so legs are at a 90 degree angle or handles are at mid-chest.',
            'Step 2: Grip the handles while elbows are slightly below shoulders.',
            'Step 3: Use handle to adjust for desired range of motion.',
            'Step 4: While keeping shoulders back against pad, press out to a fully extended arm position and return with a controlled movement.',
            ],  
  ),
  Equipment(id: '23', 
            name: 'Decline Press', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
  ),
  Equipment(id: '24', 
            name: 'Dual Adjustable Pulley', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
  ),
  Equipment(id: '25', 
            name: 'Flat Bench Press', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
  ),
  Equipment(id: '26', 
            name: 'Incline Press', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
  ),
  Equipment(id: '27', 
            name: 'Leg Extension', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust back of seat to align pivot point at the knee and lower leg pad comfortably above ankle.',
            'Step 2: Adjust input to desired range of motion.',
            'Step 3: With thighs parallel and feet relaxed, slowly straighten legs to full extension.',
            'Step 4: Return weight with controlled movement to starting position.',
            ],  
  ),
  Equipment(id: '28', 
            name: 'Pectoral Fly', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions:[
            'Step 1: Adjust seat height so elbows are slightly below shoulders.',
            'Step 2: Adjust start position using overhead range of motion adjustments for each arm.',
            'Step 3: Sit with chest up, shoulders back and grip vertical handles with elbows slightly bent. Pull handles together with a smooth motion.',
            'Step 4: Return weight with controlled movement to starting position.',
            ],  
  ),
  Equipment(id: '29', 
            name: 'Plate Loaded Shoulder Press', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat height so handles are level with top of shoulders.',
            'Step 3: Grip handles and sit firmly against back pad with chest up and shoulders back.',
            'Step 4: Press handles up to a full over-head position without locking elbows and return.', 
            ],  
  ),
  Equipment(id: '30', 
            name: 'Plate Loaded Front Pull Down', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat height so top of the chest pad is at mid chest and adjust thigh pads so they are firmly in place over the thigh.',
            'Step 3: Grip handles with an underhand grip and sit.',
            'Step 4: Pull handles to shoulders and slowly return using controlled movement.',
            ],  
  ),
  Equipment(id: '31', 
            name: 'Plate Loaded Row', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat height based on your height and comfort. Place your feet on one of the two foot pegs for comfort and variety.',
            'Step 3: Sit up tall and grip handles in the position desired.',
            'Step 4: Pull handles to chest and slowly return using controlled movement.',
            ],  
  ),
  Equipment(id: '32', 
            name: 'Plate Loaded Linear Leg Press', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust the back pad by pulling the lever, based on height and comfort. You may also adjust your range of motion on the center lever.',
            'Step 3: Sit with back against the back pad and place your feet on foot plate, hip width apart. Push away slightly to release the rack mechanism.',
            'Step 4: Grip handles, bend knees in, and press away.',
            ],  
  ),
  Equipment(id: '33', 
            name: 'Preacher Curl', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat for your height. Upper arms rest comfortably on the top of the pad and legs at a 90 degree angle.',
            'Step 3: Elbows should align with the pivot point. Palms up and pull to shoulders with controlled movement and return to starting position.',
            ],  
  ),
  Equipment(id: '34', 
            name: 'Pulldown', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height with lever under seat so handles are level with top of shoulders.',
            'Step 2: Grip handles while back is firmly against seat with chest up and shoulders back.',
            'Step 3: Press handles up with a full overhead position without locking (fully extending) elbows and return with a controlled movement.',       
            ],  
  ),
  Equipment(id: '35', 
            name: 'Treadmill', 
            imageURL: 'https://picsum.photos/200', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
  ),
];