import 'equipment.dart';

final List<Equipment> ListOfEquipment = [
  Equipment(id: '0', 
            name: 'Abdominal', 
            imageURL: 'assets/images/abdominal_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height with lever under seat so legs are at 90 degree angle or the middle of torso is aligned with pivot point.',
            'Step 2: Place elbows on pads and grip handles.',
            'Step 3: Pull chest towards hips by contracting abdominals. Return to start position with controlled movement.',
            ],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Core'],
  ),
  Equipment(id: '1', 
            name: 'Adjustable Bench', 
            imageURL: 'assets/images/adjustable_bench_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Various'], 
  ),
  Equipment(id: '2', 
            name: 'Assist Dip/Chin', 
            imageURL: 'assets/images/chin_dip_assist_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
              'Step 1: Step up and rotate handles to inner or outer position. Grip handles and place knees on pad.',
              'Step 2: Lower body with a controlled movement-torso upright/shoulders back. Do not exceed your comfortable range of motion. Return slowly.',
              'Step 3: When finished, bring knee pad all the way up to bring weight stack to rest.',
              'Step 4: Carefully step backwards onto steps and back down to floor.',
              'Step 1: Step up and grip desired hand position. Place knees on pad.',
              'Step 2: Slowly pull body upwards, then return with controlled movement, keeping chest up throughout the exercise.',
              'Step 3: When finished, bring knee pad all the way up to bring weight stack to rest.',
              'Step 4: Carefully step backwards onto steps and back down to floor.',
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Back', 'Arms', 'Shoulders'],
  ),
  Equipment(id: '3', 
            name: 'Back Extension', 
            imageURL: 'assets/images/back_extension_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Back', 'Glutes'],
  ),
  Equipment(id: '4', 
            name: 'Battle Ropes', 
            imageURL: 'assets/images/battle_ropes_image.png', 
            // url used: https://www.trxtraining.com/cdn/shop/products/IMG_8378_1200x.jpg?v=1663694807
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Cardio', 'Core'], 
  ),
  Equipment(id: '5', 
            name: 'Biceps Curl', 
            imageURL: 'assets/images/biceps_curl_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
              'Step 1: Adjust seat height so elbows align with pivot point (just off end of pad).',
              'Step 2: Grip handles firmly.',
              'Step 3: Keeping upper arms on pads, bend arms slowly to curled position and return.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Biceps'],
  ),
  Equipment(id: '6', 
            name: 'BOSU Balance Trainer', 
            imageURL: 'assets/images/bosu_image.png', 
            // url used: https://target.scene7.com/is/image/Target/GUEST_a768c296-1698-4a46-b7a7-3dae8ec4c5e0?wid=488&hei=488&fmt=pjpeg
            // BOTTOM OVERFLOW
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Core'],  
  ),
  Equipment(id: '7', 
            name: 'Calf Extension', 
            imageURL: 'assets/images/calf_extension_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
              'Step 1: Sit in seat and place feet on foot platform.',
              'Step 2: Adjust back pad so that knees are slightly bent while feet are on platform.',
              'Step 3: Slowly extend ankles. Keeping lower back and hips against back pad, and return.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Calves'],
  ),
  Equipment(id: '8', 
            name: 'Calf Raise', 
            imageURL: 'assets/images/calf_raise_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions:[
              'Step 1: Load plates on each side for proper resistance',
              'Step 2: Sit and position your feet onto the foot pad. Lower the knee pad to your thighs and sit up tall.',
              'Step 3: Lift up and move release lever to the side.',
              'Step 4: Grip handles. Slowly, lower and lift through heels, pushing up through the balls of your feet.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Calves'],
  ),
  Equipment(id: '9', 
            name: 'Chest Press', 
            imageURL: 'assets/images/chest_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height with lever under seat so legs are at a 90 degree angle or handles are at mid-chest.',
            'Step 2: Grip the handles while elbows are slightly below shoulders.',
            'Step 3: Use handle to adjust for desired range of motion.',
            'Step 4: While keeping shoulders back against pad, press out to a fully extended arm position and return with a controlled movement.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Chest'],
  ),
  Equipment(id: '10', 
            name: 'Concept 2 Model E Rowers', 
            imageURL: 'assets/images/concept_model_rowers_image.png', 
            // url used: https://m.media-amazon.com/images/I/51q3XF78h-L._AC_UF1000,1000_QL80_.jpg
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Cardio', 'Back', 'Legs'],
  ),
  Equipment(id: '11', 
            name: 'Cybex Arc Trainers', 
            imageURL: 'assets/images/cybex_arc_trainers_image.png', 
            // url used: https://m.media-amazon.com/images/I/61NbK3XcKLL._AC_UF1000,1000_QL80_.jpg
            // BOTTOM OVERFLOW
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Cardio', 'Legs', 'Arms'], 
  ),
  Equipment(id: '12', 
            name: 'Decline Bench', 
            imageURL: 'assets/images/decline_bench_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
            pushPull: ['Push'],
            legsBackChest: ['Chest'],  
  ),
  Equipment(id: '13', 
            name: 'Decline Press', 
            imageURL: 'assets/images/decline_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push'],
            legsBackChest: ['Chest'], 
  ),
  Equipment(id: '14', 
            name: 'Dual Adjustable Pulley', 
            imageURL: 'assets/images/dual_adjustable_pulley_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: [],
  ),
  Equipment(id: '15', 
            name: 'Flat Bench Press', 
            imageURL: 'assets/images/flat_bench_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push'],
            legsBackChest: ['Chest'],
  ),
  Equipment(id: '16', 
            name: 'Free Weights', 
            imageURL: 'assets/images/free_weights_image.png', 
            // url used: https://xmarkfitness.com/cdn/shop/products/3107.1-2_960x_crop_center.jpg?v=1674678150
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Range from 5 lb up to 125 lb',
            ],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: [],
  ),
  Equipment(id: '17', 
            name: 'Hip Abduction', 
            imageURL: 'assets/images/hip_abduction_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [
            'Step 1: Sit down with feet on foot pegs so knees are bent at a 90 degree angle.',
            'Step 2: Adjust range of motion with the lever on the side of machine.',
            'Step 3: Move the pads inward and return to starting position using controlled movement.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Outer Thights'],
  ),
  Equipment(id: '18', 
            name: 'Hip Adduction', 
            //shrink this one next!
            imageURL: 'assets/images/hip_adduction_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [
            'Step 1: Sit down with feet on foot pegs so knees are bent at a 90 degree angle.',
            'Step 2: Adjust range of motion with the lever on the side of machine.',
            'Step 3: Move the pads outward and return to starting position using a controlled movement.',
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Inner Thighs'],
  ),
  Equipment(id: '19', 
            name: 'Incline Press', 
            imageURL: 'assets/images/incline_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push'],
            legsBackChest: ['Chest'],
  ),
  Equipment(id: '20', 
            name: 'Kettlebells', 
            imageURL: 'assets/images/kettlebells_image.png', 
            // url used: https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6433/6433799_sd.jpg
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Core', 'Cardio'],
  ),
  Equipment(id: '21', 
            name: 'Leg Extension', 
            imageURL: 'assets/images/leg_extension_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust back of seat to align pivot point at the knee and lower leg pad comfortably above ankle.',
            'Step 2: Adjust input to desired range of motion.',
            'Step 3: With thighs parallel and feet relaxed, slowly straighten legs to full extension.',
            'Step 4: Return weight with controlled movement to starting position.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Quadriceps'],
  ),
  Equipment(id: '22', 
            name: 'Life Fitness Bikes (Upright)', 
            imageURL: 'assets/images/life_fitness_bikes_upright_image.png', 
            // url used: https://media.cmsmax.com/vefu49lnk4rjnbzhxrrlx/life-fitness-clsc-upright-bike-remanufactured.jpg
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Legs', 'Cardio'], 
  ),
  Equipment(id: '23', 
            name: 'Life Fitness Bikes (Recumbent)', 
            imageURL: 'assets/images/life_fitness_bikes_recumbent_image.png', 
            // url used: https://equipyourgym.com/wp-content/uploads/2019/07/image-22.png
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Legs', 'Carido'], 
  ),
  Equipment(id: '24', 
            name: 'Life Fitness Free Weights', 
            imageURL: 'assets/images/life_fitness_free_weights_image.png', 
            // url used: https://shop.lifefitness.com/cdn/shop/products/signature-series-two-tier-dumbbell-rack-platinum-life-fitness-1000x1000_1200x1200.jpg?v=1636062829
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [
            'Range from 5 lb up to 125 lb',
            ],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Various'],
  ),
  Equipment(id: '25', 
            name: 'Life Fitness Synergy', 
            imageURL: 'assets/images/life_fitness_synergy_image.png', 
            // url used: https://www.lifefitness.com/resource/image/35502/portrait_ratio1x1/400/400/699c1cc35c8f78531085499d959ed00d/gK/synrgy360-t-combo-package-plat.png
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Various'],
  ),
  Equipment(id: '26', 
            name: 'Life Fitness Treadmills', 
            imageURL: 'assets/images/life_fitness_treadmills_image.png', 
            // url used: https://m.media-amazon.com/images/I/61qIHKf8V3L._AC_UF1000,1000_QL80_.jpg
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Legs', 'Cardio'],
  ),
  Equipment(id: '27', 
            name: 'Olympic Lifting Racks', 
            imageURL: 'assets/images/olympic_lifting_racks_image.png', 
            // url used: https://valorfitness.com/cdn/shop/products/bd-58bpf-half-rack-w-weightlifting-platform-1_720x.jpg?v=1680889756
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body'],
  ),
  Equipment(id: '28', 
            name: 'Pectorial Fly', 
            imageURL: 'assets/images/pectoral_fly_delt_fly_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions:[
            'Step 1: Adjust seat height so elbows are slightly below shoulders.',
            'Step 2: Adjust start position using overhead range of motion adjustments for each arm.',
            'Step 3: Sit with chest up, shoulders back and grip vertical handles with elbows slightly bent. Pull handles together with a smooth motion.',
            'Step 4: Return weight with controlled movement to starting position.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Chest'],
  ),
  Equipment(id: '29', 
            name: 'Plate Loaded Shoulder Press', 
            imageURL: 'assets/images/plate_loaded_shoulder_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat height so handles are level with top of shoulders.',
            'Step 3: Grip handles and sit firmly against back pad with chest up and shoulders back.',
            'Step 4: Press handles up to a full over-head position without locking elbows and return.', 
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Shoulders'],
  ),
  Equipment(id: '30', 
            name: 'Plate Loaded Front Pull Down', 
            imageURL: 'assets/images/plate_loaded_front_pull_down_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat height so top of the chest pad is at mid chest and adjust thigh pads so they are firmly in place over the thigh.',
            'Step 3: Grip handles with an underhand grip and sit.',
            'Step 4: Pull handles to shoulders and slowly return using controlled movement.',
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Back'],
  ),
  Equipment(id: '31', 
            name: 'Plate Loaded Row', 
            imageURL: 'assets/images/plate_loaded_row_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat height based on your height and comfort. Place your feet on one of the two foot pegs for comfort and variety.',
            'Step 3: Sit up tall and grip handles in the position desired.',
            'Step 4: Pull handles to chest and slowly return using controlled movement.',
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Back'],
  ),
  Equipment(id: '32', 
            name: 'Plate Loaded Linear Leg Press', 
            imageURL: 'assets/images/plate_loaded_linear_leg_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust the back pad by pulling the lever, based on height and comfort. You may also adjust your range of motion on the center lever.',
            'Step 3: Sit with back against the back pad and place your feet on foot plate, hip width apart. Push away slightly to release the rack mechanism.',
            'Step 4: Grip handles, bend knees in, and press away.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Legs'],
  ),
  Equipment(id: '33', 
            name: 'Preacher Curl', 
            imageURL: 'assets/images/preacher_curl_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Load plates on each side for proper resistance.',
            'Step 2: Adjust seat for your height. Upper arms rest comfortably on the top of the pad and legs at a 90 degree angle.',
            'Step 3: Elbows should align with the pivot point. Palms up and pull to shoulders with controlled movement and return to starting position.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Biceps'],
  ),
  Equipment(id: '34', 
            name: 'Precor Adaptive Motion Trainer', 
            imageURL: 'assets/images/precor_adaptive_motion_trainer_image.png', 
            // url used: https://m.media-amazon.com/images/I/81HYpQDLoEL._AC_UF1000,1000_QL80_.jpg
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Cardio'],
  ),
  Equipment(id: '35', 
            name: 'Precor Elliptical Fitness Cross-Trainer', 
            imageURL: 'assets/images/precor_elliptical_fitness_cross_trainer_image.png', 
            // url used: https://m.media-amazon.com/images/I/61PFSk1iGWL._AC_UF1000,1000_QL80_.jpg
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Cardio'],
  ),
  Equipment(id: '36', 
            name: 'Pulldown', 
            imageURL: 'assets/images/pulldown_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height with lever under seat so handles are level with top of shoulders.',
            'Step 2: Grip handles while back is firmly against seat with chest up and shoulders back.',
            'Step 3: Press handles up with a full overhead position without locking (fully extending) elbows and return with a controlled movement.',       
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Back'],
  ),
  Equipment(id: '37', 
            name: 'Rear Deltoid', 
            imageURL: 'assets/images/row_rear_deltoid_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height so arms are parallel to floor while holding inside handles.',
            'Step 2: Sit facing pad and grip handles firmly.',
            'Step 3: With elbows bent slightly, rotate handles out and back, keeping elbows at grip height.',
            'Step 4: Return weight with controlled movement to starting position.',
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Shoulders'],
  ),
  Equipment(id: '38', 
            name: 'Row Deltoid', 
            imageURL: 'assets/images/row_rear_deltoid_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height to align mid-chest with top of chest pad.',
            'Step 2: Adjust chest pad to allow arms to fully extend.',
            'Step 3: Sit tall with head and chest up and grip desired handles.',
            'Step 4: Pull handles back slowly until elbows are alongside body and return. ',
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Back'],
  ), 
  Equipment(id: '39', 
            name: 'Schwinn Airdynes', 
            imageURL: 'assets/images/schwinn_airdynes_image.png', 
            // url used: https://www.schwinnfitness.com/dw/image/v2/AAYW_PRD/on/demandware.static/-/Sites-nautilus-master-catalog/default/dw154ed6d3/images/schwinn/airdyne-bikes/ad7/100625/schwinn-airdyne-ad7-1.png?sw=700&sh=700&sm=fit
            // BOTTOM OVERLFOW
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Cardio'],
  ),
  Equipment(id: '40', 
            name: 'SciFit Pro 1 Upper-Body', 
            imageURL: 'assets/images/scifit_pro_upper_body_image.png', 
            // url used: https://shop.lifefitness.com/cdn/shop/products/SCIFIT-Upper-Body-PRO1-premium-001-WHT-1000x1000_1.jpg?v=1617029360&width=1000
            // BOTTOM OVERFLOW
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Various'], 
  ),
  Equipment(id: '41', 
            name: 'Seated Leg Curl', 
            imageURL: 'assets/images/seated_leg_curl_image.png', 
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [
            'Step 1: Adjust back of seat to align pivot point at the knee and ankle pad to align with the back of the ankle.',
            'Step 2: Adjust input for desired range of motion.',
            'Step 3: With legs on top of ankle pad, lower the thigh pad comfortably against legs and grip handles.',
            'Step 4: Slowly curl legs down and return to starting position using controlled movement.',
            ],  
            pushPull: ['Pull'],
            legsBackChest: ['Hamstrings'],
  ),
  Equipment(id: '42', 
            name: 'Seated Leg Press', 
            imageURL: 'assets/images/seated_leg_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust start position for desired range of motion.',
            'Step 2: Place feet on foot plate and grip handles.',
            'Step 3: Slowly push against platform until knees are slightly bent, keeping lower back and hips against pads at all times.',
            'Step 4: Return weight with controlled movement to starting position.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Legs'],
  ),
  Equipment(id: '43', 
            name: 'Shoulder Press', 
            imageURL: 'assets/images/shoulder_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height so handles are level with top of shoulders.',
            'Step 2: Grip handles and sit firmly against back pad with chest up and shoulders back.',
            'Step 3: Press handles up to a full over-head position without locking elbows and return.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Shoulders'],
  ),
  Equipment(id: '44', 
            name: 'Squat Racks', 
            imageURL: 'assets/images/squat_racks_image.png', 
            // url used: https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRmogUjJF4K9sKd7oViHvCw3X2WZkpNcg_PD4BbAPERCjP6jXABicVkprdfu5vQ_Vq9qmIRc8mm
            // BOTTOM OVERFLOW
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Legs'],
  ),
  Equipment(id: '45', 
            name: 'Stability Balls', 
            imageURL: 'assets/images/stability_balls_image.png', 
            // url used: https://www.gaiam.com/cdn/shop/products/05-51980-line-55ball-A.jpg?v=1588972863
            // BOTTOM OVERFLOW
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: [],
            legsBackChest: ['Core', 'Stability'],
  ),
  Equipment(id: '46', 
            name: 'Stairmaster Freeclimb', 
            imageURL: 'assets/images/stairmaster_freeclimb_image.png', 
            // url used: https://m.media-amazon.com/images/I/511Vq5k-yGL._AC_UF1000,1000_QL80_.jpg
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Legs', 'Cardio'],
  ),
  Equipment(id: '47', 
            name: 'Stairmaster Stepmill', 
            imageURL: 'assets/images/stairmaster_stepmill_image.png', 
            // url used: https://m.media-amazon.com/images/I/51+XpVEdVyL._AC_UF1000,1000_QL80_.jpg
            // BOTTOM OVERFLOW
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Legs', 'Cardio'],
  ),
  Equipment(id: '48', 
            name: 'Star Trac eSpinners', 
            imageURL: 'assets/images/star_trac_espinners_image.png', 
            // url used: https://m.media-amazon.com/images/I/71zDskfSLIL._AC_UF1000,1000_QL80_.jpg
            //
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [], 
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Legs', 'Cardio'],
  ),
  Equipment(id: '49', 
            name: 'Torso Rotation', 
            imageURL: 'assets/images/torso_rotation_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat position for desired range of motion. Place knees on the front edge of seat pad while facing chest pads.',
            'Step 2: Adjust chest support pad so that the center of the pads align with top of chest.',
            'Step 3: Grasp handles and rotate torso . Be sure knees are placed against support pads. Return slowly to starting position.',
            'Step 4: Rotate seat position to train opposite side of torso.',
            ],  
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Core', 'Obliques'],
  ),
  Equipment(id: '50', 
            name: 'Triceps Press', 
            imageURL: 'assets/images/triceps_press_image.png', 
            availableAtGyms: ['0'], 
            isMachine: true, 
            instructions: [
            'Step 1: Adjust seat height so you are able to comfortably grip handles.',
            'Step 2: Rotate both handles to inner or outer position.',
            'Step 3: While keeping back against pad and elbows close to side of body, slowly press handles down without locking elbows at bottom and return.',
            ],  
            pushPull: ['Push'],
            legsBackChest: ['Triceps'],
  ),
  Equipment(id: '51', 
            name: 'TRX Rip and Suspension Trainers', 
            imageURL: 'assets/images/trx_rip_suspension_trainers_image.png', 
            // url used: https://www.trxtraining.com/cdn/shop/products/TRX5-21-21v21441_R2_1200x.jpg?v=1663784556
            availableAtGyms: ['0'], 
            isMachine: false, 
            instructions: [],
            pushPull: ['Push', 'Pull'],
            legsBackChest: ['Full Body', 'Core', 'Stability'],
  ),
];